const COMMAND_INIT = 0x1;
const COMMAND_PRINT = 0x2;
const COMMAND_DATA = 0x4;
const COMMAND_STATUS = 0xf;

const STATE_AWAIT_MAGIC_BYTES = 0;
const STATE_AWAIT_COMMAND = 1;
const STATE_AWAIT_COMPRESSION_INFO = 2;
const STATE_AWAIT_PACKET_DATA_LENGTH = 3;
const STATE_AWAIT_DATA = 4;
const STATE_AWAIT_CHECKSUM = 5;
const STATE_AWAIT_KEEPALIVE = 6;
const STATE_AWAIT_STATUS_QUERY = 7;

const EMPTY_PACKET = {
  command: null,
  buffer: [],
  data: [],
  hasCompression: null,
  dataLength: 0,
  checksum: 0,
};

module.exports = {
  COMMAND_INIT,
  COMMAND_PRINT,
  COMMAND_DATA,
  COMMAND_STATUS,
  STATE_AWAIT_MAGIC_BYTES,
  STATE_AWAIT_COMMAND,
  STATE_AWAIT_COMPRESSION_INFO,
  STATE_AWAIT_PACKET_DATA_LENGTH,
  STATE_AWAIT_DATA,
  STATE_AWAIT_CHECKSUM,
  STATE_AWAIT_KEEPALIVE,
  STATE_AWAIT_STATUS_QUERY,
  EMPTY_PACKET,
};
